services:
  adguardhome:
    image: adguard/adguardhome:v0.107.55
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /volume2/docker/adguard/conf:/opt/adguardhome/conf
      - /volume2/docker/adguard/work:/opt/adguardhome/work
      - /etc/network/interfaces:/etc/network/interfaces:ro
      - /etc/network/interfaces.d:/etc/network/interfaces.d:ro