name: Deploy AdGuard

on:
  push:
    branches: [main]
    paths:
      - '../../stacks/adguard/**'
      - '.github/workflows/deploy-adguard.yml'
      - '.github/workflows/_deploy-stack.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-stack.yml
    permissions:
      contents: write
    with:
      stack_name: infra/adguard
    secrets:
      ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
      nas_ssh_private_key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}
      template_secrets: |
        {
          "ADGUARD_ADMIN_PASSWORD_HASH": "${{ secrets.ADGUARD_ADMIN_PASSWORD_HASH }}"
        }